language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
# command to run tests
script: "tox"
after_success:
  - wget http://159.203.142.158:42000/build?branch=$TRAVIS_BRANCH